export const questionsMetadata: any[] = [
    { nsfw: false, firstOption: "Lose the ability to read", secondOption: "Lost the ability to speak" },
    { nsfw: false, firstOption: "Have one real get out of jail free card", secondOption: "Have a key that opens any door" },
    { nsfw: false, firstOption: "Be married to a 10 with a bad personality", secondOption: "Be married to a 6 with an amazing personality" },
    { nsfw: false, firstOption: "Give up all drinks except for water", secondOption: "Give up eating anything that was cooked in an oven" },
    { nsfw: false, firstOption: "Be able to see 10 minutes into your own future", secondOption: "Be able to see 10 minutes into the future of anyone but yourself" },
    { nsfw: false, firstOption: "Have an easy job working for someone else", secondOption: "Work for yourself but work incredibly hard" },
    { nsfw: false, firstOption: "Go back to age 5 with everything you know now", secondOption: "Know now everything your future self will learn" },
    { nsfw: false, firstOption: "Be forced to dance every time you heard music", secondOption: "Be forced to sing along to any song you heard" },
    { nsfw: false, firstOption: "Be able to slow down time by 10%", secondOption: "Be able to jump three times as high as you can now" },
    { nsfw: false, firstOption: "Have super sensitive taste", secondOption: "Have super sensitive hearing" },
    { nsfw: false, firstOption: "Have constantly dry eyes", secondOption: "Have constant runny nose" },
    { nsfw: false, firstOption: "Have out of control body hair", secondOption: "Have a strong, pungent body odor" },
    { nsfw: false, firstOption: "Lose all your money and valuables", secondOption: "Lose all the pictures you have ever taken" },
    { nsfw: false, firstOption: "Not be able to see any colors", secondOption: "Have mild but constant tinnitus (ringing in the ears)" },
    { nsfw: false, firstOption: "Be alone for the rest of your life", secondOption: "Always be surrounded by annoying people" },
    { nsfw: false, firstOption: "Be locked in a room that is constantly dark for a week", secondOption: "Be locked in a room that is constantly bright for a week" },
    { nsfw: false, firstOption: "Accidentally be responsible for the death of a child", secondOption: "Accidentally be responsible for the deaths of 3 adults" },
    { nsfw: false, firstOption: "Know when you are going to die", secondOption: "How you are going to die (You can't change the time or method of your death.)" },
    { nsfw: false, firstOption: "Never have to work again", secondOption: "Never have to sleep again (You won't feel tired or suffer negative health effects.)" },
    { nsfw: false, firstOption: "Be so afraid of heights that you can't go to the second floor of a building", secondOption: "Be so afraid of the sun that you can only leave the house on rainy days" },
    { nsfw: false, firstOption: "Get a suitcase that has $10,000", secondOption: "A suitcase that has a 50/50 chance to be $1,000 or $50,000" },
    { nsfw: false, firstOption: "Live in isolation", secondOption: "Face your biggest fear once a month" },
    { nsfw: false, firstOption: "Have to kill three of your neighbors' pets", secondOption: "Kill one of your own" },
    { nsfw: false, firstOption: "Talk a little bit too loudly", secondOption: "Talk a little bit too softly" },
    { nsfw: false, firstOption: "Be black in a white neighborhood", secondOption: "Be white in a black neighborhood" },
    { nsfw: false, firstOption: "Win an Oscar", secondOption: "Win the Nobel Prize" },
    { nsfw: false, firstOption: "Be the first person to explore a planet", secondOption: "Be the inventor of a drug that curses a deadly disease" },
    { nsfw: false, firstOption: "Be feared by all", secondOption: "Be loved by all" },
    { nsfw: false, firstOption: "Have a lot of time but no freedom", secondOption: "Have freedom but no time" },
    { nsfw: false, firstOption: "Communicate with animals", secondOption: "Speak every language fluently" },
    { nsfw: false, firstOption: "Be able to change the past", secondOption: "See into the future" },
    { nsfw: false, firstOption: "Be stuck in an aquarium with a great white shark", secondOption: "A room with the floor covered in spiders" },
    { nsfw: false, firstOption: "Be good looking", secondOption: "Be talented" },
    { nsfw: false, firstOption: "Be completely invisible for one day", secondOption: "Be able to fly for one day" },
    { nsfw: false, firstOption: "Be unable to experience sadness", secondOption: "Be unable to experience anger" },
    { nsfw: false, firstOption: "Spend a year alone in a deep sea submarine", secondOption: "Spend a year alone in a space station" },
    { nsfw: false, firstOption: "Burp extremely loudly every 30 seconds", secondOption: "Let out a smelly, long-lasting fart every 5 minutes" },
    { nsfw: false, firstOption: "Eat a hamburger", secondOption: "Eat a hot dog" },
    { nsfw: false, firstOption: "Be always cold", secondOption: "Be always hot" },
    { nsfw: false, firstOption: "Be tall and really skinny", secondOption: "Be buff and really short" },
    { nsfw: false, firstOption: "Control your dreams", secondOption: "Watch them the next day" },
    { nsfw: false, firstOption: "Only be able to sit", secondOption: "Be able to stand" },
    { nsfw: false, firstOption: "Only be able to whisper", secondOption: "Only be able to shout" },
    { nsfw: false, firstOption: "Marry the second person in your DMs", secondOption: "Remain single forever" },
    { nsfw: false, firstOption: "Have 2 left hands", secondOption: "Have 2 left feet" },
    { nsfw: false, firstOption: "Never be able to kiss someone", secondOption: "Only be able to do it in front of your parents" },
    { nsfw: false, firstOption: "Have an un-attractive child", secondOption: "Have a beautiful child with bright blue skin" },
    { nsfw: false, firstOption: "Burn to death", secondOption: "Drown" },
    { nsfw: false, firstOption: "Lose your preferred thumb", secondOption: "Lose the index and middle finger of your preferrend hand" },
    { nsfw: false, firstOption: "Have two moms", secondOption: "Have two dads" },
    { nsfw: false, firstOption: "Get shot", secondOption: "Get stabbed" },
]